typography_spectrum: 0.8999421189073473
color:
  brandStrength: 0.03965000482276082
  lightness: 0.998874701326713
  saturation: 0.6523166783154011
  rhythmicContrast: 0.4823891380801797
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
layout_spectrum: 0.9093081476166844
name: SOLANT - Raum für Gesundheit
title: SOLANT
description: Raum für Gesundheit
